spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all
      properties:
        max.in.flight.requests.per.connection: 1

app:
  kafka:
    topic: event-scores
  external-api:
    base-url: http://localhost:8081
  polling:
    interval-seconds: 10
